import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./style/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Th!nkTr!p",
  description: "Generated by no4hh4on",
  icons: {
    icon: "/TT.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <img className="cloud1" src="/images/cloud1.png" alt="cloud1" />
        <img className="cloud2" src="/images/cloud2.png" alt="cloud2" />
      </body>
    </html>
  );
}
